name: Child Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  run-child:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: echo "Hello from child: ${{ inputs.name }}"


